# Generated by Django 3.2 on 2024-05-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchtime',
            name='total_watch_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
